use proc_macro2::{Span, TokenStream};
use quote::quote;
use syn::parse::{Parse, ParseStream, Result};
use syn::{Ident, LitStr, Token, Type, braced, bracketed, parenthesized};

use super::util::type_last_ident;

// ─── Parsing ────────────────────────────────────────────────────────────

pub(crate) struct StateGraphInput {
    pub machine_name: Ident,
    pub states: Vec<StateDef>,
    pub transitions: Vec<TransitionDef>,
}

pub(crate) struct StateDef {
    pub variant: Ident,
    pub label: LitStr,
    pub icon: LitStr,
}

pub(crate) struct TransitionDef {
    pub from: Ident,
    pub message: Type,
    pub to: Ident,
    pub label: LitStr,
    pub icon: LitStr,
}

impl Parse for StateGraphInput {
    fn parse(input: ParseStream) -> Result<Self> {
        let machine_name: Ident = input.parse()?;
        let _: Token![,] = input.parse()?;

        // States block: { Variant => ("label", "icon"), ... }
        let states_content;
        braced!(states_content in input);
        let mut states = Vec::new();
        if !states_content.is_empty() {
            states.push(states_content.parse()?);
            loop {
                let lookahead = states_content.lookahead1();
                if lookahead.peek(Token![,]) {
                    let _: Token![,] = states_content.parse()?;
                    if states_content.is_empty() {
                        break;
                    }
                    states.push(states_content.parse()?);
                } else {
                    break;
                }
            }
        }
        let _: Token![,] = input.parse()?;

        // Transitions block: [ (From, Msg) => To => ("label", "icon"), ... ]
        let trans_content;
        bracketed!(trans_content in input);
        let mut transitions = Vec::new();
        if !trans_content.is_empty() {
            transitions.push(trans_content.parse()?);
            loop {
                let lookahead = trans_content.lookahead1();
                if lookahead.peek(Token![,]) {
                    let _: Token![,] = trans_content.parse()?;
                    if trans_content.is_empty() {
                        break;
                    }
                    transitions.push(trans_content.parse()?);
                } else {
                    break;
                }
            }
        }

        Ok(StateGraphInput {
            machine_name,
            states,
            transitions,
        })
    }
}

impl Parse for StateDef {
    fn parse(input: ParseStream) -> Result<Self> {
        let variant: Ident = input.parse()?;
        let _: Token![=>] = input.parse()?;
        let tuple_content;
        parenthesized!(tuple_content in input);
        let label: LitStr = tuple_content.parse()?;
        let _: Token![,] = tuple_content.parse()?;
        let icon: LitStr = tuple_content.parse()?;
        Ok(StateDef {
            variant,
            label,
            icon,
        })
    }
}

impl Parse for TransitionDef {
    fn parse(input: ParseStream) -> Result<Self> {
        let paren_content;
        parenthesized!(paren_content in input);
        let from: Ident = paren_content.parse()?;
        let _: Token![,] = paren_content.parse()?;
        let message: Type = paren_content.parse()?;

        let _: Token![=>] = input.parse()?;
        let to: Ident = input.parse()?;
        let _: Token![=>] = input.parse()?;

        let tuple_content;
        parenthesized!(tuple_content in input);
        let label: LitStr = tuple_content.parse()?;
        let _: Token![,] = tuple_content.parse()?;
        let icon: LitStr = tuple_content.parse()?;

        Ok(TransitionDef {
            from,
            message,
            to,
            label,
            icon,
        })
    }
}

// ─── Expansion ──────────────────────────────────────────────────────────

pub(crate) fn expand(input: &StateGraphInput) -> TokenStream {
    let machine_name = &input.machine_name;

    // Type names derived from the machine name
    let node_ty = Ident::new(&format!("{}StateNode", machine_name), machine_name.span());
    let edge_ty = Ident::new(
        &format!("{}TransitionEdge", machine_name),
        machine_name.span(),
    );
    let graph_ty = Ident::new(&format!("{}Graph", machine_name), machine_name.span());

    // Struct definitions
    let structs = quote! {
        /// Auto-generated by `state_graph!` — a state node definition.
        #[derive(Clone, Debug, PartialEq)]
        pub struct #node_ty {
            pub name: &'static str,
            pub label: &'static str,
            pub icon: &'static str,
        }

        /// Auto-generated by `state_graph!` — a directed transition edge.
        #[derive(Clone, Debug, PartialEq)]
        pub struct #edge_ty {
            pub from: &'static str,
            pub to: &'static str,
            pub message: &'static str,
            pub label: &'static str,
            pub icon: &'static str,
        }

        /// Auto-generated by `state_graph!` — a complete state machine graph.
        #[derive(Clone, Debug, PartialEq)]
        pub struct #graph_ty {
            pub name: &'static str,
            pub states: &'static [#node_ty],
            pub transitions: &'static [#edge_ty],
        }
    };

    // State entries
    let state_entries: Vec<_> = input
        .states
        .iter()
        .map(|s| {
            let name_lit = LitStr::new(&s.variant.to_string(), s.variant.span());
            let label = &s.label;
            let icon = &s.icon;
            quote! {
                #node_ty { name: #name_lit, label: #label, icon: #icon }
            }
        })
        .collect();

    // Transition entries
    let trans_entries: Vec<_> = input
        .transitions
        .iter()
        .map(|t| {
            let from_lit = LitStr::new(&t.from.to_string(), t.from.span());
            let to_lit = LitStr::new(&t.to.to_string(), t.to.span());
            let msg_lit = LitStr::new(
                &type_last_ident(&t.message).to_string(),
                Span::call_site(),
            );
            let label = &t.label;
            let icon = &t.icon;
            quote! {
                #edge_ty { from: #from_lit, to: #to_lit, message: #msg_lit, label: #label, icon: #icon }
            }
        })
        .collect();

    let name_lit = LitStr::new(&machine_name.to_string(), machine_name.span());

    let graph_fn = quote! {
        impl #machine_name {
            /// Returns the static state machine graph definition.
            pub fn graph() -> #graph_ty {
                #graph_ty {
                    name: #name_lit,
                    states: &[#(#state_entries),*],
                    transitions: &[#(#trans_entries),*],
                }
            }
        }
    };

    let mut output = TokenStream::new();
    output.extend(structs);
    output.extend(graph_fn);
    output
}
